apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-variables
  namespace: default
  labels:
    app: postgres
data:
  POSTGRES_USER: "auser"
  POSTGRES_PASSWORD: "apassword"
  POSTGRES_DB: "models_database"
  SQLALCHEMY_DATABASE_URI: "postgresql://auser:apassword@postgres/models_database"
  SECRET_KEY: "mysecretkey"
  DEBUG: "1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: romal200/mlops:latest
          ports:
            - containerPort: 5000
          env:
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  key: SQLALCHEMY_DATABASE_URI
                  name: environment-variables
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: environment-variables
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: environment-variables

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: environment-variables
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: environment-variables
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: environment-variables
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
